"""Initial migration

Revision ID: a20021b26015
Revises: b293e9fb6a5c
Create Date: 2025-04-08 16:16:58.036134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20021b26015'
down_revision: Union[str, None] = 'b293e9fb6a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('users_username', sa.String(length=15), nullable=False),
    sa.Column('users_hashed_password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('users_username')
    )
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_title', sa.String(length=30), nullable=False),
    sa.Column('task_description', sa.String(length=50), nullable=True),
    sa.Column('task_is_complete', sa.Boolean(), nullable=False),
    sa.Column('task_date', sa.DateTime(), nullable=True),
    sa.Column('task_priority', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('users')
    # ### end Alembic commands ###
